---

- name: "key: Generate signing key {{ poudriere_conf_pkg_repo_signing_key }}"
  community.crypto.openssl_privatekey:
    attributes: "{{ poudriere_key_attributes|default(omit) }}"
    backup: "{{ poudriere_key_backup|default(omit) }}"
    cipher: "{{ poudriere_key_cipher|default(omit) }}"
    curve: "{{ poudriere_key_curve|default(omit) }}"
    force: "{{ poudriere_key_force|default(omit) }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_ssl_private_key_mode }}"
    owner: "{{ poudriere_owner }}"
    passphrase: "{{ poudriere_key_passphrase|default(omit) }}"
    path: "{{ poudriere_conf_pkg_repo_signing_key }}"
    # regenerate: "{{ poudriere_key_regenerate|default(omit) }}"
    # return_content: "{{ poudriere_key_return_content|default(omit) }}"
    select_crypto_backend: "{{ poudriere_key_select_crypto_backend|default(omit) }}"
    selevel: "{{ poudriere_key_selevel|default(omit) }}"
    serole: "{{ poudriere_key_serole|default(omit) }}"
    setype: "{{ poudriere_key_setype|default(omit) }}"
    seuser: "{{ poudriere_key_seuser|default(omit) }}"
    size: "{{ poudriere_key_size }}"
    state: "{{ poudriere_key_state|default(omit) }}"
    type: "{{ poudriere_key_type }}"
    unsafe_writes: "{{ poudriere_key_unsafe_writes|default(omit) }}"
- name: "key: Generate signing crt {{ poudriere_key_crt }}"
  ansible.builtin.command:
    cmd: "{{ poudriere_key_cmd }}"
    creates: "{{ poudriere_key_crt }}"

# EOF
...
